### ISSUE TITLE
Dragon Nuance required ? 

### ISSUE THREAD

**Issue by sambaPython24** [mrob95/mathfly-talon#1]
Hey, I find your project very interesting and would like to know, wether it is required to have a version of Nuance Dragon on your computer. If so, could you specify, which version of Nuance one needs (Professional, Home, Anywhere ...)?

**Comment by mirober** [comment]
The project is built on top of [talon](https://talonvoice.com/), which has its own free speech engine built in, as well as integrating with Dragon.

If you're just getting started then I would recommend using talon's speech recognition, which is getting better very quickly and will soon surpass Dragon.
