### ISSUE TITLE
Folder Structure of integrated mathfly-talon folder

### ISSUE THREAD

**Issue by sambaPython24** [mrob95/mathfly-talon#2]
Hey, could you write into your readme file, how the folder structure should look like after copied into the user folder. Is

```talon\user\knausj_talon-master\...```
```talon\user\mathfly-talon-master\...[latex.py;lyx.py]```

correct, i.e. should knausj_talon and mathfly_talon be next to each other or integrated into each other?

**Comment by mirober** [comment]
Yes, the way you have it in your example will work fine. Talon loads every `.py` and `.talon` file inside every folder in `user`, so theoretically you could lay it out however you like. Keeping mathfly files separate from knausj is sensible though - I'll add a note to the readme

**Comment by sambaPython24** [comment]
Thank you for the answer and your work here.
